const handleJWTUnauthorizedErrors = require("./handleJWTUnauthorizedErrors");
const handleHTTPErrors = require("./handleHTTPErrors");
const handleObjectionJSErrors = require("./handleObjectionjsErrors");
const handleStrongParamErrors = require("./handleStrongParamErrors");
const { logErrors, consoleLogErrors } = require("./logErrors");

const useMiddlewares = (app) => {
  app.use(consoleLogErrors); //             Log errors to the console
  app.use(logErrors); //                    Log errors to a logfile
  app.use(handleJWTUnauthorizedErrors); //  Handle 401s generated by auth0 jwt validation
  app.use(handleStrongParamErrors); //      Handle responding if strong-params throws an error
  app.use(handleObjectionJSErrors); //      Handle responding if objectionjs throws an error
  app.use(handleHTTPErrors); //             Handle responding for common error types
};

module.exports = useMiddlewares;
